CREATE TABLE `personal_tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`text` text NOT NULL,
	`done` int NOT NULL DEFAULT 0,
	`taskKind` enum('at_time','by_deadline') NOT NULL DEFAULT 'by_deadline',
	`dueDate` timestamp,
	`createdBy` int NOT NULL,
	`createdByName` text NOT NULL,
	`assignType` enum('self','personal','team','all') NOT NULL DEFAULT 'self',
	`assignTeam` enum('身体','天理','郡山北部','郡山南部'),
	`assignUserId` int,
	`assignUserName` text,
	`repeatType` enum('none','daily','weekly','biweekly','monthly','nth_weekday') NOT NULL DEFAULT 'none',
	`repeatDayOfWeek` int,
	`repeatDayOfMonth` int,
	`repeatMonthInterval` int DEFAULT 1,
	`repeatNthWeek` int,
	`repeatNthDayOfWeek` int,
	`repeatEndDate` timestamp,
	`completedBy` int,
	`completedAt` timestamp,
	`deletedAt` timestamp,
	`deletedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `personal_tasks_id` PRIMARY KEY(`id`)
);
